### ISSUE TITLE
Add repo to copier-template topic so it can more easily be found.

### ISSUE THREAD

**Issue by ssteinerx** [matagus/django-app-starter#1]
### Description

From the [**copier-template** topic page:](https://github.com/topics/copier-template):
 
To associate your repository with the **copier-template** topic, visit your repo's landing page and select "manage topics."

[Github article on topics](https://docs.github.com/en/articles/classifying-your-repository-with-topics)

**Comment by matagus** [comment]
<img width="404" alt="Screenshot 2024-03-13 at 2 45 55 PM" src="https://github.com/matagus/django-app-starter/assets/58519/27c47095-ec63-4e1c-897e-378b74202d7b">

Done, thanks!

**Comment by ssteinerx** [comment]
Sorry, was it already there? Wasn't coming up in search for some reason.  Does now; all good.  Thanks!
